/**
 * @file simulator-narrative.ts
 * @description Simulator-specific AI narrative generation service.
 *
 * Converts a SimulationResult snapshot into a concise, three-part narrative:
 *   - Observation  — what the numbers say
 *   - Implication  — what it means for the environment
 *   - Suggested Action — one concrete next step
 *
 * ## Design Constraints
 * - Gemini Flash is the primary generator (requires GEMINI_API_KEY env var).
 * - Falls back to deterministic templates when the API key is absent or the
 *   call fails, ensuring the UI never breaks.
 * - Output is capped at 120 words / 2–4 sentences to keep it scannable.
 * - No database writes — narratives are ephemeral and caller-scoped.
 * - No React, no Supabase — safe to call from any server context.
 */

import { GoogleGenerativeAI } from '@google/generative-ai'

// ============================================================
// Public types
// ============================================================

/**
 * The three-part narrative structure returned for a simulation scenario.
 * All three strings are populated regardless of whether Gemini or the
 * deterministic fallback was used.
 */
export interface SimulatorNarrative {
  /** One sentence describing what the simulation numbers show. */
  observation: string
  /** One sentence on the real-world environmental meaning. */
  implication: string
  /** One concrete, actionable suggestion for the user. */
  suggestedAction: string
  /**
   * `true` when this narrative was generated by Gemini.
   * `false` when the deterministic fallback was used.
   */
  isAiGenerated: boolean
}

/**
 * Input data required to generate a simulator narrative.
 * Mirrors the relevant fields from {@link SimulationResult}.
 */
export interface SimulatorNarrativeInput {
  currentCarbonScore: number
  projectedCarbonScore: number
  carbonReduction: number
  reductionPercentage: number | null
  ecosystemImprovement: {
    forestHealth: number
    waterQuality: number
    airQuality: number
    biodiversity: number
  }
}

// ============================================================
// Deterministic fallback templates
// ============================================================

/**
 * Returns a deterministic, template-based narrative based on the
 * reduction percentage bucket. Used as a fallback when Gemini is
 * unavailable or returns an error.
 *
 * @internal
 */
function buildFallbackNarrative(input: SimulatorNarrativeInput): SimulatorNarrative {
  const { carbonReduction, reductionPercentage, ecosystemImprovement } = input

  const pct = reductionPercentage ?? 0

  // Identify the strongest ecosystem improvement dimension for the implication
  const improvements = [
    { label: 'air quality', value: ecosystemImprovement.airQuality },
    { label: 'forest health', value: ecosystemImprovement.forestHealth },
    { label: 'water quality', value: ecosystemImprovement.waterQuality },
    { label: 'biodiversity', value: ecosystemImprovement.biodiversity },
  ]
  const topImprovement = improvements.reduce((a, b) => (a.value >= b.value ? a : b))
  const hasEcosystemGain = topImprovement.value > 0

  // No change scenario
  if (carbonReduction === 0 || pct === 0) {
    return {
      observation: 'Your simulated changes result in no net difference in carbon emissions.',
      implication: 'The ecosystem remains in its current state — try adjusting transport type or dietary choices for a more impactful scenario.',
      suggestedAction: 'Experiment with switching to cycling, public transport, or a plant-rich diet to see measurable change.',
      isAiGenerated: false,
    }
  }

  // Regression scenario (more carbon)
  if (carbonReduction < 0) {
    const absPct = Math.abs(pct).toFixed(1)
    return {
      observation: `This scenario increases your emissions by ${Math.abs(carbonReduction)} kg CO₂e (${absPct}% more than your baseline).`,
      implication: 'Higher emissions accelerate ecosystem stress — air quality, water health, and biodiversity all decline with rising CO₂.',
      suggestedAction: 'Consider reducing travel distance, switching to a cleaner transport mode, or lowering energy usage to reverse this trend.',
      isAiGenerated: false,
    }
  }

  // Improvement — bucket by percentage
  const pctLabel = pct.toFixed(1)

  if (pct < 15) {
    return {
      observation: `Your simulated changes reduce emissions by ${carbonReduction} kg CO₂e (${pctLabel}% improvement).`,
      implication: hasEcosystemGain
        ? `Even small reductions support ${topImprovement.label} recovery — every kg of CO₂ saved counts.`
        : 'Small, consistent reductions accumulate into meaningful environmental benefit over time.',
      suggestedAction: 'Try combining multiple lifestyle changes — such as reducing driving distance and switching to a vegetarian diet — to amplify the impact.',
      isAiGenerated: false,
    }
  }

  if (pct < 40) {
    return {
      observation: `Your simulated changes reduce emissions by ${carbonReduction} kg CO₂e (${pctLabel}% reduction).`,
      implication: hasEcosystemGain
        ? `A meaningful reduction like this tangibly improves ${topImprovement.label}, giving local ecosystems space to recover.`
        : 'A meaningful reduction like this reduces atmospheric burden and supports cleaner air and water systems.',
      suggestedAction: 'Lock in these gains by making this scenario a regular habit — consistency matters more than perfection.',
      isAiGenerated: false,
    }
  }

  // >= 40% reduction
  return {
    observation: `Your simulated changes cut emissions by ${carbonReduction} kg CO₂e — a ${pctLabel}% reduction from your baseline.`,
    implication: hasEcosystemGain
      ? `Reductions of this scale accelerate ${topImprovement.label} recovery and create positive feedback loops across the entire ecosystem.`
      : 'Reductions of this scale create lasting positive pressure on air quality, water health, and biodiversity.',
    suggestedAction: 'These are high-impact choices worth prioritising — even applying them two or three times a week would make a significant difference.',
    isAiGenerated: false,
  }
}

// ============================================================
// Gemini prompt builder
// ============================================================

/**
 * Builds the text prompt sent to Gemini Flash.
 * Keeps the context minimal to reduce token cost and encourage
 * concise outputs within the 120-word ceiling.
 *
 * @internal
 */
function buildPrompt(input: SimulatorNarrativeInput): string {
  const { currentCarbonScore, projectedCarbonScore, carbonReduction, reductionPercentage, ecosystemImprovement } = input

  const pctStr = reductionPercentage !== null ? `${reductionPercentage}%` : 'unknown%'

  const ecoLines = [
    `Forest Health: ${ecosystemImprovement.forestHealth > 0 ? '+' : ''}${ecosystemImprovement.forestHealth}`,
    `Water Quality: ${ecosystemImprovement.waterQuality > 0 ? '+' : ''}${ecosystemImprovement.waterQuality}`,
    `Air Quality: ${ecosystemImprovement.airQuality > 0 ? '+' : ''}${ecosystemImprovement.airQuality}`,
    `Biodiversity: ${ecosystemImprovement.biodiversity > 0 ? '+' : ''}${ecosystemImprovement.biodiversity}`,
  ].join(', ')

  return `You are an environmental awareness writer for a carbon footprint app.

A user has run a "what-if" simulation with these results:
- Current carbon score: ${currentCarbonScore} kg CO₂e
- Projected carbon score: ${projectedCarbonScore} kg CO₂e
- Carbon reduction: ${carbonReduction > 0 ? '+' : ''}${carbonReduction} kg CO₂e (${carbonReduction >= 0 ? '-' : '+'}${pctStr})
- Ecosystem changes (0–100 scale): ${ecoLines}

Write exactly three short sentences — each one a standalone statement. Use plain, clear language.

Return ONLY a valid JSON object with these three fields (no markdown, no backticks, no preamble):
{
  "observation": "<one sentence describing what the simulation numbers show>",
  "implication": "<one sentence on the real-world environmental meaning>",
  "suggestedAction": "<one concrete, actionable suggestion for the user>"
}

Rules:
- Maximum 120 words total across all three sentences.
- Do not use the words "significant" or "crucial".
- Do not repeat numbers already stated in the observation.
- Be specific — reference the actual improvement or degradation direction.
- If the scenario is worse than baseline, reflect that honestly.`
}

// ============================================================
// Gemini parsing
// ============================================================

interface RawNarrative {
  observation?: unknown
  implication?: unknown
  suggestedAction?: unknown
}

/**
 * Attempts to parse and validate a Gemini response text into a
 * {@link SimulatorNarrative}. Returns `null` if parsing fails.
 *
 * @internal
 */
function parseGeminiResponse(text: string): SimulatorNarrative | null {
  try {
    // Strip any accidental markdown fences
    const cleaned = text
      .replace(/```json\s*/gi, '')
      .replace(/```\s*/gi, '')
      .trim()

    const parsed = JSON.parse(cleaned) as RawNarrative

    const observation = typeof parsed.observation === 'string' ? parsed.observation.trim() : ''
    const implication = typeof parsed.implication === 'string' ? parsed.implication.trim() : ''
    const suggestedAction = typeof parsed.suggestedAction === 'string' ? parsed.suggestedAction.trim() : ''

    if (!observation || !implication || !suggestedAction) {
      return null
    }

    return { observation, implication, suggestedAction, isAiGenerated: true }
  } catch {
    return null
  }
}

// ============================================================
// Public API
// ============================================================

/**
 * Generates a three-part simulator narrative for the given simulation input.
 *
 * Attempts to use Gemini Flash when `GEMINI_API_KEY` is set and the API
 * call succeeds. Falls back to a deterministic template-based narrative
 * in all other cases (missing key, network error, parse failure).
 *
 * **Never throws.** Callers always receive a fully populated
 * {@link SimulatorNarrative} regardless of Gemini availability.
 *
 * @param input - Key metrics from the simulation result.
 * @returns A {@link SimulatorNarrative} with observation, implication, and
 *          suggestedAction populated.
 */
export async function generateSimulatorNarrative(
  input: SimulatorNarrativeInput,
): Promise<SimulatorNarrative> {
  const apiKey = process.env.GEMINI_API_KEY

  // Skip Gemini entirely if no key is configured
  if (!apiKey) {
    return buildFallbackNarrative(input)
  }

  try {
    const genAI = new GoogleGenerativeAI(apiKey)
    const model = genAI.getGenerativeModel({
      model: 'gemini-2.0-flash',
      generationConfig: {
        // Low temperature for factual, consistent outputs
        temperature: 0.3,
        maxOutputTokens: 300,
      },
    })

    const prompt = buildPrompt(input)
    const result = await model.generateContent(prompt)
    const text = result.response.text()

    const narrative = parseGeminiResponse(text)
    if (narrative) {
      return narrative
    }

    // Parse failed — fall through to deterministic fallback
    console.warn('[simulator-narrative] Gemini response could not be parsed, using fallback.')
    return buildFallbackNarrative(input)
  } catch (err) {
    // Network error, quota exceeded, etc. — never surface this to the user
    console.error('[simulator-narrative] Gemini call failed, using fallback:', err)
    return buildFallbackNarrative(input)
  }
}
